src/Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using KalahariTickets.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KalahariTickets.Models.ClientsViewModels;
using KalahariTickets.Models;

namespace KalahariTickets.Controllers
{
    /// <summary>
    /// Controller for Clients
    /// </summary>
    [Authorize]
    public partial class ClientsController : Controller
    {
        private KalahariTicketsContext _context;

        /// <summary>
        /// Initializes _context
        /// </summary>
        /// <param name="context">context of client</param>
        public ClientsController(KalahariTicketsContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Shows all clients
        /// </summary>
        /// <returns>clients page</returns>
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var clients = await _context.Clients.GroupJoin(_context.Tickets.Where(ticket => ticket.Open), client => client.Id, ticket => ticket.ClientId, (client, tickets) => new ClientDetails { Client = client, Tickets = tickets, OpenTicketCount = tickets.Count() }).OrderByDescending(details => details.Tickets.Count()).ToListAsync();
            return View(clients);
        }

        /// <summary>
        /// Opens a client's details
        /// </summary>
        /// <param name="id">The id of the client</param>
        /// <returns>The client</returns>
        [HttpGet]
        public async Task<IActionResult> Open([FromRoute] Guid id)
        {
            var client = await _context.Clients.FindAsync(id);
            var tickets = await _context.Tickets.Where(ticket => ticket.ClientId == id).ToListAsync();

            var details = new ClientDetails {
                Client = client,
                OpenTicketCount = tickets.Count,
                Tickets = tickets
            };
            return View(details);
        }

        /// <summary>
        /// Gets the add client view
        /// </summary>
        /// <returns>The add client view.</returns>
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Adds a client to the database
        /// </summary>
        /// <param name="client">The client to add</param>
        /// <returns>The added client</returns>
        [HttpPost]
        public async Task<IActionResult> Add([FromForm] Client client)
        {
            client.DateAdded = DateTime.Now;
            _context.Clients.Add(client);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Open), new { id = client.Id });
        }

        /// <summary>
        /// Gets view for adding a ticket.
        /// </summary>
        /// <returns>The view.</returns>
        [HttpGet]
        public IActionResult AddTicket([FromRoute] Guid id)
        {
            return View(new Ticket { ClientId = id });
        }

        /// <summary>
        /// Adds a ticket
        /// </summary>
        /// <param name="ticket">The ticket to be added</param>
        /// <returns>The added ticket</returns>
        [HttpPost]
        public async Task<IActionResult> AddTicket([FromForm] Ticket ticket)
        {
            ticket.DateAdded = DateTime.Now;
            ticket.IsUrgent = false;
            ticket.Open = true;

            _context.Tickets.Add(ticket);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(TicketsController.Open), "Tickets", new { id = ticket.Id });
        }
    }
}

src/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using KalahariTickets.Data;
using KalahariTickets.Models;
using KalahariTickets.Models.ReportsViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KalahariTickets.Controllers
{
    /// <summary>
    /// For handling reports
    /// </summary>
    [Authorize(Roles = DataConstants.AdministratorRole)]
    public class ReportsController : Controller
    {
        private KalahariTicketsContext _context;

        /// <summary>
        /// Initializes this controller
        /// </summary>
        /// <param name="context">context of the technician</param>
        public ReportsController(KalahariTicketsContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets the report view
        /// </summary>
        /// <returns>The report view</returns>
        [HttpGet]
        public async Task<IActionResult> All()
        {
            // var timeSpan = new TimeSpan(hours: 24, minutes: 0, seconds: 0);
            // var end = DateTime.Now;
            // var start = end - timeSpan;

            // var openEvents = (await _context.Tickets.Where(ticket => ticket.DateAdded > start || (ticket.DateAdded <= start && (ticket.DateClosed > start || ticket.Open))).Select(ticket => ticket.DateAdded < start ? start : ticket.DateAdded).ToListAsync()).Select(time => (time, true));
            // var closeEvents = (await _context.Tickets.Where(ticket => ticket.DateClosed > start).Select(ticket => ticket.DateClosed).ToListAsync()).Select(time => (time, false));

            // var events = new List<IEnumerable<(DateTime, bool)>> { openEvents, closeEvents }.SelectMany(ticket => ticket); OrderBy<IQueryable<(DateTime, bool)>, bool>((time, open) => true);

            var details = new ReportDetails
            {
                AverageQueueLength = await _context.Tickets.Where(ticket => ticket.Open).CountAsync(),
                AverageWait = new TimeSpan(0, 0, 0),
                EmptyQueuePercentage = 0,
                TicketsNotAddressedSameDay = 15,
                TechnicianIdleHours = await _context.Users.GroupJoin(_context.TechnicianTicketTimes, technician => technician.UserName, time => time.TechnicianId, (technician, times) => new { Technician = technician, Time = 8 }).ToAsyncEnumerable().Select(techTime => (techTime.Technician, techTime.Time)).ToList()
            };
            return View(details);
        }
    }
}

src/Controllers/TechniciansController.cs
using System;
using System.Threading.Tasks;
using KalahariTickets.Data;
using KalahariTickets.Models;
using KalahariTickets.Models.TechniciansViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KalahariTickets.Controllers
{
    /// <summary>
    /// Controller for technicians
    /// </summary>
    [Authorize(Roles = DataConstants.AdministratorRole)]
    public class TechniciansController : Controller
    {
        private KalahariTicketsContext _context;

        private UserManager<Technician> _userManager;

        /// <summary>
        /// intializes _context
        /// </summary>
        /// <param name="context">context of the technician</param>
        /// <param name="userManager">the usermanager</param>
        public TechniciansController(KalahariTicketsContext context, UserManager<Technician> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// Gets all technicians
        /// </summary>
        /// <returns>A list of all technicians</returns>
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var technicians = await _context.Users.ToListAsync();
            return View(technicians);
        }

        /// <summary>
        /// Gets the view for adding a technician
        /// </summary>
        /// <returns>The add technician view</returns>
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Adds a technician
        /// </summary>
        /// <returns>The technician list</returns>
        [HttpPost]
        public async Task<IActionResult> Add([FromForm] NewTechnician newTechnician)
        {
            var technician = new Technician
            {
                DateAdded = DateTime.Now,
                UserName = $"{newTechnician.FirstName}.{newTechnician.LastName}",
                FirstName = newTechnician.FirstName,
                LastName = newTechnician.LastName,
                IsAdmin = newTechnician.IsAdmin
            };
            await _userManager.CreateAsync(technician, newTechnician.Password);
            if (technician.IsAdmin)
            {
                await _userManager.AddToRoleAsync(technician, DataConstants.AdministratorRole);
            }
            return RedirectToAction(nameof(All));
        }
    }
}

src/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity 
@using KalahariTickets.Models
@using KalahariTickets.Data
@inject SignInManager<Technician> SignInManager 
@inject UserManager<Technician> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - Kalahari Tickets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css" media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    @RenderSection("Style", required: false)
</head>

<body>
    <nav class="green darken-4">
        <div class="nav-wrapper green darken-4 container">
            <a class="brand-logo hide-on-med-and-down"><strong class="amber-text text-darken-2"> Kalahari Tickets </strong> </a>
            <ul class="right amber-text text-darken-2">
                @if (SignInManager.IsSignedIn(User)) {
                <li class="nav-item amber-text text-darken-2" >
                    Hello @UserManager.GetUserName(User)!
                </li>
                <li class="nav-item amber-text text-darken-2">
                    <a asp-controller="Account" asp-action="Logout">Log out</a>
                </li>
                } 
                else 
                {
                <li class="nav-item amber-text text-darken-2">
                    <a asp-controller="Account" asp-action="Login">Log in</a>
                </li>
                }
                <li>
                    <a asp-controller="Tickets" asp-action="All">Tickets</a>
                </li>
                <li>
                    <a asp-controller="Clients" asp-action="All">Clients</a>
                </li>
                @if (User.IsInRole(DataConstants.AdministratorRole)) {
                <li>
                    <a asp-controller="Technicians" asp-action="All">Technicians</a>
                </li>
                <li>
                    <a asp-controller="Reports" asp-action="All">Reports</a>
                </li>
                }
            </ul>
        </div>
    </nav>
    <main class="container">
        <h1 id="Title">@ViewData["Title"]</h1>
        @RenderBody()
    </main>

    @RenderSection("Scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js" crossorigin=" anonymous "></script>
</body>

</html>